apiVersion: apps/v1
kind: Deployment                    
metadata:
  name: demo-standalone          
  labels:                          
    app: teacup-app
spec:
  selector:
    matchLabels:                   
      app: teacup-app
      tier: mysql
  strategy:
    type: Recreate
  template:                        
    metadata:
      labels:                       
        app: teacup-app
        tier: mysql
    spec:                           
      containers:
      - image: mysql:5.6            
        name: mysql
        env:                       
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:                
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: database
        ports:
        - containerPort: 3306            
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  
          mountPath: /var/lib/mysql
      volumes:                       
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
