apiVersion: v1
kind: Service
metadata:
  name: demo-standalone
  labels:
    app: teacup-app
spec:
  ports:
    - port: 3306
  selector:
      app: teacup-app
      tier: mysql
  clusterIP: None


apiVersion: v1
kind: Service
metadata:
  name: demo-standalone
spec:
  type: NodePort
  selector:                        
    app: teacup-app
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306