---
apiVersion: apps/v1          
kind: Deployment             
metadata:
  name: teacup-web-server   
  labels:                    
    app: teacup-web-server
spec:
  replicas: 1                
  selector:
    matchLabels:             
      app: teacup-web-server
  template:                   
    metadata:
      labels:                 
        app: teacup-web-server
    spec:                    
      containers:
      - name: teacup-web-server
        image: vens6910/demo-fe:v2.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: teacup-web-server   
  labels:                     
    app: teacup-web-server
spec:
  type: NodePort
  selector:
    app: teacup-web-server
  ports:
     - protocol: TCP
       port: 80
       targetPort: 80



