---
apiVersion: apps/v1          
kind: Deployment             
metadata:
  name: teacup-app-server   
  labels:                    
    app: teacup-app-server
spec:
  replicas: 1                
  selector:
    matchLabels:             
      app: teacup-app-server
  template:                   
    metadata:
      labels:                 
        app: teacup-app-server
    spec:                    
      containers:
      - name: teacup-app-server
        image: vens6910/tea-be:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8086
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:                  
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:          
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: teacup-app-server   
  labels:                     
    app: teacup-app-server
spec:                         
  type: NodePort               
  selector:
    app: teacup-app-server   
  ports:                     
  - name: http
    port: 8086
    targetPort: 8086


